// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backends.sql

package db

import (
	"context"
)

const deleteBackend = `-- name: DeleteBackend :execrows
DELETE FROM backends WHERE name = $1
`

func (q *Queries) DeleteBackend(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackend, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackend = `-- name: GetBackend :one

SELECT name, endpoint, model_id, api_key_env_var, max_concurrency,
       input_cost_per_mtoken, output_cost_per_mtoken, quality,
       created_at, updated_at, rate_per_second,
       kind, tool_kind, cost_per_gpu_second
FROM backends
WHERE name = $1
`

// The SELECT column order matches the canonical backends table order.
// Keeping that order lets sqlc reuse the db.Backend row type instead of
// emitting a per-query row type.
func (q *Queries) GetBackend(ctx context.Context, name string) (Backend, error) {
	row := q.db.QueryRow(ctx, getBackend, name)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Quality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RatePerSecond,
		&i.Kind,
		&i.ToolKind,
		&i.CostPerGpuSecond,
	)
	return i, err
}

const insertBackend = `-- name: InsertBackend :one
INSERT INTO backends (
    name, endpoint, model_id, api_key_env_var, max_concurrency,
    input_cost_per_mtoken, output_cost_per_mtoken, quality, rate_per_second,
    kind, tool_kind, cost_per_gpu_second
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING name, endpoint, model_id, api_key_env_var, max_concurrency,
          input_cost_per_mtoken, output_cost_per_mtoken, quality,
          created_at, updated_at, rate_per_second,
          kind, tool_kind, cost_per_gpu_second
`

type InsertBackendParams struct {
	Name                string
	Endpoint            string
	ModelID             *string
	ApiKeyEnvVar        string
	MaxConcurrency      int32
	InputCostPerMtoken  *float64
	OutputCostPerMtoken *float64
	Quality             *float64
	RatePerSecond       *float64
	Kind                string
	ToolKind            *string
	CostPerGpuSecond    *float64
}

func (q *Queries) InsertBackend(ctx context.Context, arg InsertBackendParams) (Backend, error) {
	row := q.db.QueryRow(ctx, insertBackend,
		arg.Name,
		arg.Endpoint,
		arg.ModelID,
		arg.ApiKeyEnvVar,
		arg.MaxConcurrency,
		arg.InputCostPerMtoken,
		arg.OutputCostPerMtoken,
		arg.Quality,
		arg.RatePerSecond,
		arg.Kind,
		arg.ToolKind,
		arg.CostPerGpuSecond,
	)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Quality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RatePerSecond,
		&i.Kind,
		&i.ToolKind,
		&i.CostPerGpuSecond,
	)
	return i, err
}

const listBackends = `-- name: ListBackends :many
SELECT name, endpoint, model_id, api_key_env_var, max_concurrency,
       input_cost_per_mtoken, output_cost_per_mtoken, quality,
       created_at, updated_at, rate_per_second,
       kind, tool_kind, cost_per_gpu_second
FROM backends
ORDER BY name
`

func (q *Queries) ListBackends(ctx context.Context) ([]Backend, error) {
	rows, err := q.db.Query(ctx, listBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backend{}
	for rows.Next() {
		var i Backend
		if err := rows.Scan(
			&i.Name,
			&i.Endpoint,
			&i.ModelID,
			&i.ApiKeyEnvVar,
			&i.MaxConcurrency,
			&i.InputCostPerMtoken,
			&i.OutputCostPerMtoken,
			&i.Quality,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RatePerSecond,
			&i.Kind,
			&i.ToolKind,
			&i.CostPerGpuSecond,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackend = `-- name: UpdateBackend :one
UPDATE backends
SET endpoint = $2,
    model_id = $3,
    api_key_env_var = $4,
    max_concurrency = $5,
    input_cost_per_mtoken = $6,
    output_cost_per_mtoken = $7,
    quality = $8,
    rate_per_second = $9,
    kind = $10,
    tool_kind = $11,
    cost_per_gpu_second = $12,
    updated_at = now()
WHERE name = $1
RETURNING name, endpoint, model_id, api_key_env_var, max_concurrency,
          input_cost_per_mtoken, output_cost_per_mtoken, quality,
          created_at, updated_at, rate_per_second,
          kind, tool_kind, cost_per_gpu_second
`

type UpdateBackendParams struct {
	Name                string
	Endpoint            string
	ModelID             *string
	ApiKeyEnvVar        string
	MaxConcurrency      int32
	InputCostPerMtoken  *float64
	OutputCostPerMtoken *float64
	Quality             *float64
	RatePerSecond       *float64
	Kind                string
	ToolKind            *string
	CostPerGpuSecond    *float64
}

func (q *Queries) UpdateBackend(ctx context.Context, arg UpdateBackendParams) (Backend, error) {
	row := q.db.QueryRow(ctx, updateBackend,
		arg.Name,
		arg.Endpoint,
		arg.ModelID,
		arg.ApiKeyEnvVar,
		arg.MaxConcurrency,
		arg.InputCostPerMtoken,
		arg.OutputCostPerMtoken,
		arg.Quality,
		arg.RatePerSecond,
		arg.Kind,
		arg.ToolKind,
		arg.CostPerGpuSecond,
	)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Quality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RatePerSecond,
		&i.Kind,
		&i.ToolKind,
		&i.CostPerGpuSecond,
	)
	return i, err
}
