// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backends.sql

package db

import (
	"context"
)

const deleteBackend = `-- name: DeleteBackend :execrows
DELETE FROM backends WHERE name = $1
`

func (q *Queries) DeleteBackend(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackend, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackend = `-- name: GetBackend :one

SELECT name, endpoint, model_id, api_key_env_var, max_concurrency,
       rate_per_second, quality, kind, tool_kind,
       input_cost_per_mtoken, output_cost_per_mtoken, rates,
       created_at, updated_at, cost_source, cache_read_cost_per_mtoken
FROM backends
WHERE name = $1
`

// The SELECT column order matches the canonical backends table order.
// Keeping that order lets sqlc reuse the db.Backend row type instead of
// emitting a per-query row type.
func (q *Queries) GetBackend(ctx context.Context, name string) (Backend, error) {
	row := q.db.QueryRow(ctx, getBackend, name)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.RatePerSecond,
		&i.Quality,
		&i.Kind,
		&i.ToolKind,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Rates,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostSource,
		&i.CacheReadCostPerMtoken,
	)
	return i, err
}

const insertBackend = `-- name: InsertBackend :one
INSERT INTO backends (
    name, endpoint, model_id, api_key_env_var, max_concurrency,
    rate_per_second, quality, kind, tool_kind,
    input_cost_per_mtoken, output_cost_per_mtoken, rates, cost_source,
    cache_read_cost_per_mtoken
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING name, endpoint, model_id, api_key_env_var, max_concurrency,
          rate_per_second, quality, kind, tool_kind,
          input_cost_per_mtoken, output_cost_per_mtoken, rates,
          created_at, updated_at, cost_source, cache_read_cost_per_mtoken
`

type InsertBackendParams struct {
	Name                   string
	Endpoint               string
	ModelID                *string
	ApiKeyEnvVar           string
	MaxConcurrency         int32
	RatePerSecond          *float64
	Quality                *float64
	Kind                   string
	ToolKind               *string
	InputCostPerMtoken     *float64
	OutputCostPerMtoken    *float64
	Rates                  []byte
	CostSource             *string
	CacheReadCostPerMtoken *float64
}

func (q *Queries) InsertBackend(ctx context.Context, arg InsertBackendParams) (Backend, error) {
	row := q.db.QueryRow(ctx, insertBackend,
		arg.Name,
		arg.Endpoint,
		arg.ModelID,
		arg.ApiKeyEnvVar,
		arg.MaxConcurrency,
		arg.RatePerSecond,
		arg.Quality,
		arg.Kind,
		arg.ToolKind,
		arg.InputCostPerMtoken,
		arg.OutputCostPerMtoken,
		arg.Rates,
		arg.CostSource,
		arg.CacheReadCostPerMtoken,
	)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.RatePerSecond,
		&i.Quality,
		&i.Kind,
		&i.ToolKind,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Rates,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostSource,
		&i.CacheReadCostPerMtoken,
	)
	return i, err
}

const listBackends = `-- name: ListBackends :many
SELECT name, endpoint, model_id, api_key_env_var, max_concurrency,
       rate_per_second, quality, kind, tool_kind,
       input_cost_per_mtoken, output_cost_per_mtoken, rates,
       created_at, updated_at, cost_source, cache_read_cost_per_mtoken
FROM backends
ORDER BY name
`

func (q *Queries) ListBackends(ctx context.Context) ([]Backend, error) {
	rows, err := q.db.Query(ctx, listBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backend{}
	for rows.Next() {
		var i Backend
		if err := rows.Scan(
			&i.Name,
			&i.Endpoint,
			&i.ModelID,
			&i.ApiKeyEnvVar,
			&i.MaxConcurrency,
			&i.RatePerSecond,
			&i.Quality,
			&i.Kind,
			&i.ToolKind,
			&i.InputCostPerMtoken,
			&i.OutputCostPerMtoken,
			&i.Rates,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CostSource,
			&i.CacheReadCostPerMtoken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackend = `-- name: UpdateBackend :one
UPDATE backends
SET endpoint = $2,
    model_id = $3,
    api_key_env_var = $4,
    max_concurrency = $5,
    rate_per_second = $6,
    quality = $7,
    kind = $8,
    tool_kind = $9,
    input_cost_per_mtoken = $10,
    output_cost_per_mtoken = $11,
    rates = $12,
    cost_source = $13,
    cache_read_cost_per_mtoken = $14,
    updated_at = now()
WHERE name = $1
RETURNING name, endpoint, model_id, api_key_env_var, max_concurrency,
          rate_per_second, quality, kind, tool_kind,
          input_cost_per_mtoken, output_cost_per_mtoken, rates,
          created_at, updated_at, cost_source, cache_read_cost_per_mtoken
`

type UpdateBackendParams struct {
	Name                   string
	Endpoint               string
	ModelID                *string
	ApiKeyEnvVar           string
	MaxConcurrency         int32
	RatePerSecond          *float64
	Quality                *float64
	Kind                   string
	ToolKind               *string
	InputCostPerMtoken     *float64
	OutputCostPerMtoken    *float64
	Rates                  []byte
	CostSource             *string
	CacheReadCostPerMtoken *float64
}

func (q *Queries) UpdateBackend(ctx context.Context, arg UpdateBackendParams) (Backend, error) {
	row := q.db.QueryRow(ctx, updateBackend,
		arg.Name,
		arg.Endpoint,
		arg.ModelID,
		arg.ApiKeyEnvVar,
		arg.MaxConcurrency,
		arg.RatePerSecond,
		arg.Quality,
		arg.Kind,
		arg.ToolKind,
		arg.InputCostPerMtoken,
		arg.OutputCostPerMtoken,
		arg.Rates,
		arg.CostSource,
		arg.CacheReadCostPerMtoken,
	)
	var i Backend
	err := row.Scan(
		&i.Name,
		&i.Endpoint,
		&i.ModelID,
		&i.ApiKeyEnvVar,
		&i.MaxConcurrency,
		&i.RatePerSecond,
		&i.Quality,
		&i.Kind,
		&i.ToolKind,
		&i.InputCostPerMtoken,
		&i.OutputCostPerMtoken,
		&i.Rates,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostSource,
		&i.CacheReadCostPerMtoken,
	)
	return i, err
}
