// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completion_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const costByMapping = `-- name: CostByMapping :many
SELECT mapping,
       COUNT(*)::bigint                            AS count,
       COALESCE(SUM(cost_usd), 0)::double precision AS total_cost_usd
FROM completion_records
WHERE created_at > COALESCE($1::timestamptz, '-infinity'::timestamptz)
GROUP BY mapping
ORDER BY mapping
`

type CostByMappingRow struct {
	Mapping      string
	Count        int64
	TotalCostUsd float64
}

// Total cost and dispatch count grouped by mapping variant, optionally
// filtered by created_at > since. The live critical path aggregates
// under the empty mapping, each shadow variant under its own name.
func (q *Queries) CostByMapping(ctx context.Context, since pgtype.Timestamptz) ([]CostByMappingRow, error) {
	rows, err := q.db.Query(ctx, costByMapping, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostByMappingRow{}
	for rows.Next() {
		var i CostByMappingRow
		if err := rows.Scan(&i.Mapping, &i.Count, &i.TotalCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageCompletions = `-- name: ListStageCompletions :many
SELECT completion_id, stage_id, workflow_run, backend, status,
       prompt_tokens, completion_tokens, latency_ms, cost_usd,
       tags, created_at, usage, tool_kind, mapping, cached_tokens
FROM completion_records
WHERE stage_id = $1
  AND created_at > COALESCE($2::timestamptz, '-infinity'::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type ListStageCompletionsParams struct {
	StageID    string
	Since      pgtype.Timestamptz
	LimitCount int32
}

type ListStageCompletionsRow struct {
	CompletionID     string
	StageID          string
	WorkflowRun      *string
	Backend          string
	Status           string
	PromptTokens     *int32
	CompletionTokens *int32
	LatencyMs        *int32
	CostUsd          *float64
	Tags             []byte
	CreatedAt        pgtype.Timestamptz
	Usage            []byte
	ToolKind         *string
	Mapping          string
	CachedTokens     *int32
}

// Returns completion records for a stage, optionally filtered by
// created_at > since. Pass a zero timestamptz to skip the filter.
func (q *Queries) ListStageCompletions(ctx context.Context, arg ListStageCompletionsParams) ([]ListStageCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listStageCompletions, arg.StageID, arg.Since, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageCompletionsRow{}
	for rows.Next() {
		var i ListStageCompletionsRow
		if err := rows.Scan(
			&i.CompletionID,
			&i.StageID,
			&i.WorkflowRun,
			&i.Backend,
			&i.Status,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.LatencyMs,
			&i.CostUsd,
			&i.Tags,
			&i.CreatedAt,
			&i.Usage,
			&i.ToolKind,
			&i.Mapping,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stageMetricsByBackend = `-- name: StageMetricsByBackend :many
SELECT backend,
       COUNT(*)::bigint                                                                AS count,
       COALESCE(AVG(latency_ms), 0)::double precision                                  AS avg_latency_ms,
       COALESCE(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY latency_ms), 0)::double precision AS p50_latency_ms,
       COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY latency_ms), 0)::double precision AS p95_latency_ms,
       COALESCE(SUM(cost_usd), 0)::double precision                                    AS total_cost_usd,
       COUNT(*) FILTER (WHERE status = 'error')::bigint                                AS error_count
FROM completion_records
WHERE stage_id = $1
  AND created_at > COALESCE($2::timestamptz, '-infinity'::timestamptz)
GROUP BY backend
ORDER BY backend
`

type StageMetricsByBackendParams struct {
	StageID string
	Since   pgtype.Timestamptz
}

type StageMetricsByBackendRow struct {
	Backend      string
	Count        int64
	AvgLatencyMs float64
	P50LatencyMs float64
	P95LatencyMs float64
	TotalCostUsd float64
	ErrorCount   int64
}

// Per-backend aggregates for a stage. Empty AVG/PERCENTILE results
// (e.g., when no rows in the window) are coalesced to 0 so callers
// don't have to deal with NULLs.
func (q *Queries) StageMetricsByBackend(ctx context.Context, arg StageMetricsByBackendParams) ([]StageMetricsByBackendRow, error) {
	rows, err := q.db.Query(ctx, stageMetricsByBackend, arg.StageID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageMetricsByBackendRow{}
	for rows.Next() {
		var i StageMetricsByBackendRow
		if err := rows.Scan(
			&i.Backend,
			&i.Count,
			&i.AvgLatencyMs,
			&i.P50LatencyMs,
			&i.P95LatencyMs,
			&i.TotalCostUsd,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
