// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCostPolicy = `-- name: GetCostPolicy :one
SELECT refresh_interval_ms, updated_at
FROM cost_policy
WHERE id = true
`

type GetCostPolicyRow struct {
	RefreshIntervalMs int32
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetCostPolicy(ctx context.Context) (GetCostPolicyRow, error) {
	row := q.db.QueryRow(ctx, getCostPolicy)
	var i GetCostPolicyRow
	err := row.Scan(&i.RefreshIntervalMs, &i.UpdatedAt)
	return i, err
}

const upsertCostPolicy = `-- name: UpsertCostPolicy :exec
INSERT INTO cost_policy (id, refresh_interval_ms, updated_at)
VALUES (true, $1, now())
ON CONFLICT (id) DO UPDATE
SET refresh_interval_ms = EXCLUDED.refresh_interval_ms,
    updated_at = now()
`

func (q *Queries) UpsertCostPolicy(ctx context.Context, refreshIntervalMs int32) error {
	_, err := q.db.Exec(ctx, upsertCostPolicy, refreshIntervalMs)
	return err
}
