// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStageFeedback = `-- name: ListStageFeedback :many
SELECT id, completion_id, stage_id, workflow_run, rating,
       labels, notes, created_at
FROM feedback
WHERE stage_id = $1
  AND created_at > COALESCE($2::timestamptz, '-infinity'::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type ListStageFeedbackParams struct {
	StageID    string
	Since      pgtype.Timestamptz
	LimitCount int32
}

func (q *Queries) ListStageFeedback(ctx context.Context, arg ListStageFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listStageFeedback, arg.StageID, arg.Since, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.CompletionID,
			&i.StageID,
			&i.WorkflowRun,
			&i.Rating,
			&i.Labels,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
