// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Backend struct {
	Name                string
	Endpoint            string
	ModelID             *string
	ApiKeyEnvVar        string
	MaxConcurrency      int32
	InputCostPerMtoken  *float64
	OutputCostPerMtoken *float64
	Quality             *float64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RatePerSecond       *float64
	Kind                string
	ToolKind            *string
	CostPerGpuSecond    *float64
}

type CompletionRecord struct {
	CompletionID     string
	StageID          string
	WorkflowRun      *string
	Backend          string
	Status           string
	PromptTokens     *int32
	CompletionTokens *int32
	LatencyMs        *int32
	CostUsd          *float64
	Tags             []byte
	CreatedAt        pgtype.Timestamptz
	GpuSeconds       *float64
	ToolKind         *string
}

type Feedback struct {
	ID           int64
	CompletionID string
	StageID      string
	WorkflowRun  *string
	Rating       *float64
	Labels       []byte
	Notes        string
	CreatedAt    pgtype.Timestamptz
}

type Stage struct {
	ID              string
	Backend         string
	ReasoningEffort string
	Labels          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
