// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Backend struct {
	Name                   string
	Endpoint               string
	ModelID                *string
	ApiKeyEnvVar           string
	MaxConcurrency         int32
	RatePerSecond          *float64
	Quality                *float64
	Kind                   string
	ToolKind               *string
	InputCostPerMtoken     *float64
	OutputCostPerMtoken    *float64
	Rates                  []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CostSource             *string
	CacheReadCostPerMtoken *float64
}

type CompletionIo struct {
	CompletionID    string
	WorkflowRun     *string
	StageID         string
	RequestContent  *string
	ResponseContent *string
	CreatedAt       pgtype.Timestamptz
}

type CompletionRecord struct {
	CompletionID     string
	StageID          string
	WorkflowRun      *string
	Backend          string
	Status           string
	PromptTokens     *int32
	CompletionTokens *int32
	Usage            []byte
	ToolKind         *string
	LatencyMs        *int32
	CostUsd          *float64
	Tags             []byte
	CreatedAt        pgtype.Timestamptz
	Mapping          string
	CachedTokens     *int32
}

type CostPolicy struct {
	ID                bool
	RefreshIntervalMs int32
	UpdatedAt         pgtype.Timestamptz
}

type Feedback struct {
	ID           int64
	CompletionID string
	StageID      string
	WorkflowRun  *string
	Rating       *float64
	Labels       []byte
	Notes        string
	CreatedAt    pgtype.Timestamptz
}

type MappingVariant struct {
	Name      string
	StageID   string
	Backend   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SchedulerPolicy struct {
	ID        bool
	Url       string
	TimeoutMs int32
	UpdatedAt pgtype.Timestamptz
}

type Stage struct {
	ID              string
	Backend         string
	ReasoningEffort string
	Labels          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Prompt          string
	CaptureIo       bool
}

type StageMapper struct {
	ID        bool
	Url       string
	TimeoutMs int32
	UpdatedAt pgtype.Timestamptz
}
