// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteBackend(ctx context.Context, name string) (int64, error)
	DeleteStage(ctx context.Context, id string) (int64, error)
	// The SELECT column order matches the canonical backends table order.
	// Keeping that order lets sqlc reuse the db.Backend row type instead of
	// emitting a per-query row type.
	GetBackend(ctx context.Context, name string) (Backend, error)
	GetStage(ctx context.Context, id string) (Stage, error)
	InsertBackend(ctx context.Context, arg InsertBackendParams) (Backend, error)
	ListBackends(ctx context.Context) ([]Backend, error)
	// Returns completion records for a stage, optionally filtered by
	// created_at > since. Pass a zero timestamptz to skip the filter.
	ListStageCompletions(ctx context.Context, arg ListStageCompletionsParams) ([]CompletionRecord, error)
	ListStageFeedback(ctx context.Context, arg ListStageFeedbackParams) ([]Feedback, error)
	ListStages(ctx context.Context) ([]Stage, error)
	ReplaceStage(ctx context.Context, arg ReplaceStageParams) (Stage, error)
	// Per-backend aggregates for a stage. Empty AVG/PERCENTILE results
	// (e.g., when no rows in the window) are coalesced to 0 so callers
	// don't have to deal with NULLs.
	StageMetricsByBackend(ctx context.Context, arg StageMetricsByBackendParams) ([]StageMetricsByBackendRow, error)
	UpdateBackend(ctx context.Context, arg UpdateBackendParams) (Backend, error)
	// Auto-create a stage with empty fields on first sighting. If the row
	// already exists, the no-op SET keeps the existing values and RETURNING
	// returns them. (A bare ON CONFLICT DO NOTHING with RETURNING returns
	// no row when the conflict fires, which loses the "fetch existing"
	// behavior we want here.)
	UpsertStageDefault(ctx context.Context, id string) (Stage, error)
}

var _ Querier = (*Queries)(nil)
