// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stages.sql

package db

import (
	"context"
)

const deleteStage = `-- name: DeleteStage :execrows
DELETE FROM stages WHERE id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStage = `-- name: GetStage :one
SELECT id, backend, reasoning_effort, labels, created_at, updated_at
FROM stages
WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id string) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Backend,
		&i.ReasoningEffort,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStages = `-- name: ListStages :many
SELECT id, backend, reasoning_effort, labels, created_at, updated_at
FROM stages
ORDER BY id
`

func (q *Queries) ListStages(ctx context.Context) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Backend,
			&i.ReasoningEffort,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceStage = `-- name: ReplaceStage :one
INSERT INTO stages (id, backend, reasoning_effort, labels, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (id) DO UPDATE
SET backend = EXCLUDED.backend,
    reasoning_effort = EXCLUDED.reasoning_effort,
    labels = EXCLUDED.labels,
    updated_at = now()
RETURNING id, backend, reasoning_effort, labels, created_at, updated_at
`

type ReplaceStageParams struct {
	ID              string
	Backend         string
	ReasoningEffort string
	Labels          []byte
}

func (q *Queries) ReplaceStage(ctx context.Context, arg ReplaceStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, replaceStage,
		arg.ID,
		arg.Backend,
		arg.ReasoningEffort,
		arg.Labels,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Backend,
		&i.ReasoningEffort,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStageDefault = `-- name: UpsertStageDefault :one
INSERT INTO stages (id, backend, reasoning_effort, labels)
VALUES ($1, '', '', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE
SET id = stages.id
RETURNING id, backend, reasoning_effort, labels, created_at, updated_at
`

// Auto-create a stage with empty fields on first sighting. If the row
// already exists, the no-op SET keeps the existing values and RETURNING
// returns them. (A bare ON CONFLICT DO NOTHING with RETURNING returns
// no row when the conflict fires, which loses the "fetch existing"
// behavior we want here.)
func (q *Queries) UpsertStageDefault(ctx context.Context, id string) (Stage, error) {
	row := q.db.QueryRow(ctx, upsertStageDefault, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Backend,
		&i.ReasoningEffort,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
