// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_mapper.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStageMapper = `-- name: GetStageMapper :one
SELECT url, timeout_ms, updated_at
FROM stage_mapper
WHERE id = true
`

type GetStageMapperRow struct {
	Url       string
	TimeoutMs int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetStageMapper(ctx context.Context) (GetStageMapperRow, error) {
	row := q.db.QueryRow(ctx, getStageMapper)
	var i GetStageMapperRow
	err := row.Scan(&i.Url, &i.TimeoutMs, &i.UpdatedAt)
	return i, err
}

const upsertStageMapper = `-- name: UpsertStageMapper :exec
INSERT INTO stage_mapper (id, url, timeout_ms, updated_at)
VALUES (true, $1, $2, now())
ON CONFLICT (id) DO UPDATE
SET url = EXCLUDED.url,
    timeout_ms = EXCLUDED.timeout_ms,
    updated_at = now()
`

type UpsertStageMapperParams struct {
	Url       string
	TimeoutMs int32
}

func (q *Queries) UpsertStageMapper(ctx context.Context, arg UpsertStageMapperParams) error {
	_, err := q.db.Exec(ctx, upsertStageMapper, arg.Url, arg.TimeoutMs)
	return err
}
