package telemetry

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/harvard-cns/orla/internal/storage"
)

// Feedback is one row in the feedback table. The developer supplies
// CompletionID and StageID; everything else is optional metadata or
// labels. ID is populated on read only — Submit ignores it (the row's
// id is generated by Postgres).
type Feedback struct {
	ID           int64     `json:"id,omitempty"`
	CompletionID string    `json:"completion_id"`
	StageID      string    `json:"stage_id"`
	WorkflowRun  string    `json:"workflow_run,omitempty"`
	Rating       *float64  `json:"rating,omitempty"`
	Labels       []string  `json:"labels,omitempty"`
	Notes        string    `json:"notes,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// FeedbackWriterConfig configures NewFeedbackWriter.
type FeedbackWriterConfig struct {
	Pool       *pgxpool.Pool
	Logger     *slog.Logger
	BufferSize int           // optional, default 4096
	BatchSize  int           // optional, default 200
	Interval   time.Duration // optional, default 200ms
}

// FeedbackWriter is a typed wrapper over storage.BatchWriter for
// feedback. Submit is non-blocking.
type FeedbackWriter struct {
	bw *storage.BatchWriter[*Feedback]
}

// NewFeedbackWriter starts a background flusher that bulk-inserts
// batches into the feedback table via pgx.CopyFrom.
func NewFeedbackWriter(cfg FeedbackWriterConfig) *FeedbackWriter {
	if cfg.Logger == nil {
		cfg.Logger = slog.Default()
	}
	bw := storage.NewBatchWriter[*Feedback](storage.BatchWriterConfig[*Feedback]{
		Name:       "feedback",
		BufferSize: cfg.BufferSize,
		BatchSize:  cfg.BatchSize,
		Interval:   cfg.Interval,
		Flush:      flushFeedback(cfg.Pool),
		Logger:     cfg.Logger,
	})
	return &FeedbackWriter{bw: bw}
}

func (w *FeedbackWriter) Submit(fb *Feedback) bool { return w.bw.Submit(fb) }
func (w *FeedbackWriter) Drops() int64             { return w.bw.Drops() }
func (w *FeedbackWriter) Flushes() int64           { return w.bw.Flushes() }
func (w *FeedbackWriter) Failures() int64          { return w.bw.Failures() }
func (w *FeedbackWriter) Close(ctx context.Context) error {
	return w.bw.Close(ctx)
}

func flushFeedback(pool *pgxpool.Pool) storage.FlushFunc[*Feedback] {
	columns := []string{
		"completion_id", "stage_id", "workflow_run",
		"rating", "labels", "notes", "created_at",
	}
	return func(ctx context.Context, items []*Feedback) error {
		conn, err := pool.Acquire(ctx)
		if err != nil {
			return fmt.Errorf("acquire conn: %w", err)
		}
		defer conn.Release()

		rows := make([][]any, 0, len(items))
		for _, fb := range items {
			labelsBytes, err := json.Marshal(fb.Labels)
			if err != nil || labelsBytes == nil {
				labelsBytes = []byte("[]")
			}
			rows = append(rows, []any{
				fb.CompletionID,
				fb.StageID,
				nullableString(fb.WorkflowRun),
				fb.Rating,
				labelsBytes,
				fb.Notes,
				fb.CreatedAt,
			})
		}

		_, err = conn.Conn().CopyFrom(ctx,
			pgx.Identifier{"feedback"},
			columns,
			pgx.CopyFromRows(rows),
		)
		if err != nil {
			return fmt.Errorf("copy feedback: %w", err)
		}
		return nil
	}
}
